// Local Routes
// GET Route
GET http://localhost:3000/users

// POST Route
###
POST http://localhost:3000/users
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "address": "1 Test Street",
    "city": "Portland",
    "state": "Oregon",
    "country": "United States of America"
}

// PUT Route
// Needs an ID
###
PUT http://localhost:3000/users/65320150d58ed4f5439d896a
content-type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "janedoe@gmail.com",
    "address": "2 Test Street",
    "city": "Portland",
    "state": "Oregon",
    "country": "United States of America"
}

// DELETE Route
// Needs an ID
###
DELETE http://localhost:3000/users/65320150d58ed4f5439d896a

// Deployment Routes
// GET Route
###
GET https://cse341-second-project.onrender.com/users

// POST Route
###
POST https://cse341-second-project.onrender.com/users
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "Address": "1 Test Street",
    "City": "Portland",
    "State": "Oregon",
    "Country": "United States of America"
}

// PUT Route
// Needs an ID
###
PUT https://cse341-second-project.onrender.com/users/65320150d58ed4f5439d896a
content-type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "janedoe@gmail.com",
    "address": "2 Test Street",
    "city": "Portland",
    "state": "Oregon",
    "country": "United States of America"
}

// DELETE Route
// Needs an ID
###
DELETE https://cse341-second-project.onrender.com/users/65320150d58ed4f5439d896a